### ISSUE TITLE
The data in data.tgz/test-set/61 were wrong

### ISSUE THREAD

**Issue by zxynbnb** [FAKEBOB-adversarial-attack/FAKEBOB#3]
The .wav files in data/data-2/test-set/61/61-70979-0039.wav and 61-70979-0040.wav are links but not wav files.

**Comment by zxynbnb** [comment]
And some other wav files are links in data.

**Comment by GolferChen** [comment]
Thanks for your feedback. We are checking the contents in data.tgz and will update it if necessary.

**Comment by FAKEBOB-adversarial-attack** [comment]
Hello, we have downloaded and checked the **data.tgz** and found everything going well.

Did you download the file correctly and completely? We have updated README and provided the MD5 for downloaded files, so here is suggestion that maybe you can check your MD5 against our provided one.

Feel free to contact for any further problem.

Best

**Comment by FAKEBOB-adversarial-attack** [comment]
Hello, sorry for our mistake. There is indeed some problem with **data.tgz**.

Previously, we checked it in Windows, under which those link files were automatically deleted and became invisible.

Now the data set has been updated.

Thanks for your feedback once again.

**Comment by wuhao2015** [comment]
Hi, I have the same problem. The data.tgz I downloaded has broken links and the md5 isn't correct. I download this on ubuntu 16.04 for several times and the problem still exists. how did you solve it ?

**Comment by wuhao2015** [comment]
@FAKEBOB-adversarial-attack @GolferChen

**Comment by FAKEBOB-adversarial-attack** [comment]
Sorry for mistake. The url for 'data.tar.gz' is wrong. Will update in short time. Thanks for feedback.

**Comment by FAKEBOB-adversarial-attack** [comment]
Hello, the url has been fixed. The correct url is:
[data.tar.gz](https://drive.google.com/file/d/1nEcobGN7_8yyYwdqs1c6XD1UTXqEyhQC/view?usp=sharing)
